### ISSUE TITLE
Add support for Pub/Sub

### ISSUE THREAD

**Issue by Sxtanna** [KDatabases/Kedis#1]

**Comment by JudeaDumont** [comment]
Damn, I needed this

**Comment by camdenorrb** [comment]
Meow D:

**Comment by Sxtanna** [comment]
Same though, however, this repo is low key sort of legacy.
I'm working on an updated version over at: https://github.com/Sxtanna/KDatabases

I currently have a new Kedis that uses bridged collections, and will have support of observing (pub/sub).
If you would like to keep up to date, or offer ideas, please feel free to star, watch, and PR :)

**Comment by Sxtanna** [comment]
(also that new kedis isn't currently in the repo, but it will be soon)
